/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.database.jdbc.rt.shared;

/**
 * Every call fails with it. It carries the first SQLException of the cause chain, when there is one.
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class FailError extends org.apache.thrift.TException implements org.apache.thrift.TBase<FailError, FailError._Fields>, java.io.Serializable, Cloneable, Comparable<FailError> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FailError");

  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TRACE_FIELD_DESC = new org.apache.thrift.protocol.TField("trace", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SQL_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("sqlState", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField VENDOR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("vendorCode", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new FailErrorStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new FailErrorTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String message; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String trace; // required
  /**
   * SQLException.getSQLState(), unset when there is no SQLException or the driver reports no state
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String sqlState; // optional
  /**
   * SQLException.getErrorCode(), unset when there is no SQLException
   */
  public int vendorCode; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE((short)1, "message"),
    TRACE((short)2, "trace"),
    /**
     * SQLException.getSQLState(), unset when there is no SQLException or the driver reports no state
     */
    SQL_STATE((short)3, "sqlState"),
    /**
     * SQLException.getErrorCode(), unset when there is no SQLException
     */
    VENDOR_CODE((short)4, "vendorCode");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE
          return MESSAGE;
        case 2: // TRACE
          return TRACE;
        case 3: // SQL_STATE
          return SQL_STATE;
        case 4: // VENDOR_CODE
          return VENDOR_CODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VENDORCODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.SQL_STATE,_Fields.VENDOR_CODE};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TRACE, new org.apache.thrift.meta_data.FieldMetaData("trace", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SQL_STATE, new org.apache.thrift.meta_data.FieldMetaData("sqlState", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VENDOR_CODE, new org.apache.thrift.meta_data.FieldMetaData("vendorCode", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FailError.class, metaDataMap);
  }

  public FailError() {
  }

  public FailError(
    java.lang.String message,
    java.lang.String trace)
  {
    this();
    this.message = message;
    this.trace = trace;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FailError(FailError other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMessage()) {
      this.message = other.message;
    }
    if (other.isSetTrace()) {
      this.trace = other.trace;
    }
    if (other.isSetSqlState()) {
      this.sqlState = other.sqlState;
    }
    this.vendorCode = other.vendorCode;
  }

  @Override
  public FailError deepCopy() {
    return new FailError(this);
  }

  @Override
  public void clear() {
    this.message = null;
    this.trace = null;
    this.sqlState = null;
    setVendorCodeIsSet(false);
    this.vendorCode = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMessage() {
    return this.message;
  }

  public FailError setMessage(@org.apache.thrift.annotation.Nullable java.lang.String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTrace() {
    return this.trace;
  }

  public FailError setTrace(@org.apache.thrift.annotation.Nullable java.lang.String trace) {
    this.trace = trace;
    return this;
  }

  public void unsetTrace() {
    this.trace = null;
  }

  /** Returns true if field trace is set (has been assigned a value) and false otherwise */
  public boolean isSetTrace() {
    return this.trace != null;
  }

  public void setTraceIsSet(boolean value) {
    if (!value) {
      this.trace = null;
    }
  }

  /**
   * SQLException.getSQLState(), unset when there is no SQLException or the driver reports no state
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSqlState() {
    return this.sqlState;
  }

  /**
   * SQLException.getSQLState(), unset when there is no SQLException or the driver reports no state
   */
  public FailError setSqlState(@org.apache.thrift.annotation.Nullable java.lang.String sqlState) {
    this.sqlState = sqlState;
    return this;
  }

  public void unsetSqlState() {
    this.sqlState = null;
  }

  /** Returns true if field sqlState is set (has been assigned a value) and false otherwise */
  public boolean isSetSqlState() {
    return this.sqlState != null;
  }

  public void setSqlStateIsSet(boolean value) {
    if (!value) {
      this.sqlState = null;
    }
  }

  /**
   * SQLException.getErrorCode(), unset when there is no SQLException
   */
  public int getVendorCode() {
    return this.vendorCode;
  }

  /**
   * SQLException.getErrorCode(), unset when there is no SQLException
   */
  public FailError setVendorCode(int vendorCode) {
    this.vendorCode = vendorCode;
    setVendorCodeIsSet(true);
    return this;
  }

  public void unsetVendorCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VENDORCODE_ISSET_ID);
  }

  /** Returns true if field vendorCode is set (has been assigned a value) and false otherwise */
  public boolean isSetVendorCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VENDORCODE_ISSET_ID);
  }

  public void setVendorCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VENDORCODE_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((java.lang.String)value);
      }
      break;

    case TRACE:
      if (value == null) {
        unsetTrace();
      } else {
        setTrace((java.lang.String)value);
      }
      break;

    case SQL_STATE:
      if (value == null) {
        unsetSqlState();
      } else {
        setSqlState((java.lang.String)value);
      }
      break;

    case VENDOR_CODE:
      if (value == null) {
        unsetVendorCode();
      } else {
        setVendorCode((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE:
      return getMessage();

    case TRACE:
      return getTrace();

    case SQL_STATE:
      return getSqlState();

    case VENDOR_CODE:
      return getVendorCode();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE:
      return isSetMessage();
    case TRACE:
      return isSetTrace();
    case SQL_STATE:
      return isSetSqlState();
    case VENDOR_CODE:
      return isSetVendorCode();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof FailError)
      return this.equals((FailError)that);
    return false;
  }

  public boolean equals(FailError that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    boolean this_present_trace = true && this.isSetTrace();
    boolean that_present_trace = true && that.isSetTrace();
    if (this_present_trace || that_present_trace) {
      if (!(this_present_trace && that_present_trace))
        return false;
      if (!this.trace.equals(that.trace))
        return false;
    }

    boolean this_present_sqlState = true && this.isSetSqlState();
    boolean that_present_sqlState = true && that.isSetSqlState();
    if (this_present_sqlState || that_present_sqlState) {
      if (!(this_present_sqlState && that_present_sqlState))
        return false;
      if (!this.sqlState.equals(that.sqlState))
        return false;
    }

    boolean this_present_vendorCode = true && this.isSetVendorCode();
    boolean that_present_vendorCode = true && that.isSetVendorCode();
    if (this_present_vendorCode || that_present_vendorCode) {
      if (!(this_present_vendorCode && that_present_vendorCode))
        return false;
      if (this.vendorCode != that.vendorCode)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMessage()) ? 131071 : 524287);
    if (isSetMessage())
      hashCode = hashCode * 8191 + message.hashCode();

    hashCode = hashCode * 8191 + ((isSetTrace()) ? 131071 : 524287);
    if (isSetTrace())
      hashCode = hashCode * 8191 + trace.hashCode();

    hashCode = hashCode * 8191 + ((isSetSqlState()) ? 131071 : 524287);
    if (isSetSqlState())
      hashCode = hashCode * 8191 + sqlState.hashCode();

    hashCode = hashCode * 8191 + ((isSetVendorCode()) ? 131071 : 524287);
    if (isSetVendorCode())
      hashCode = hashCode * 8191 + vendorCode;

    return hashCode;
  }

  @Override
  public int compareTo(FailError other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetMessage(), other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, other.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTrace(), other.isSetTrace());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTrace()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.trace, other.trace);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSqlState(), other.isSetSqlState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSqlState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sqlState, other.sqlState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVendorCode(), other.isSetVendorCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVendorCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vendorCode, other.vendorCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("FailError(");
    boolean first = true;

    sb.append("message:");
    if (this.message == null) {
      sb.append("null");
    } else {
      sb.append(this.message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("trace:");
    if (this.trace == null) {
      sb.append("null");
    } else {
      sb.append(this.trace);
    }
    first = false;
    if (isSetSqlState()) {
      if (!first) sb.append(", ");
      sb.append("sqlState:");
      if (this.sqlState == null) {
        sb.append("null");
      } else {
        sb.append(this.sqlState);
      }
      first = false;
    }
    if (isSetVendorCode()) {
      if (!first) sb.append(", ");
      sb.append("vendorCode:");
      sb.append(this.vendorCode);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FailErrorStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FailErrorStandardScheme getScheme() {
      return new FailErrorStandardScheme();
    }
  }

  private static class FailErrorStandardScheme extends org.apache.thrift.scheme.StandardScheme<FailError> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, FailError struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TRACE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.trace = iprot.readString();
              struct.setTraceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SQL_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sqlState = iprot.readString();
              struct.setSqlStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // VENDOR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.vendorCode = iprot.readI32();
              struct.setVendorCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, FailError struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(struct.message);
        oprot.writeFieldEnd();
      }
      if (struct.trace != null) {
        oprot.writeFieldBegin(TRACE_FIELD_DESC);
        oprot.writeString(struct.trace);
        oprot.writeFieldEnd();
      }
      if (struct.sqlState != null) {
        if (struct.isSetSqlState()) {
          oprot.writeFieldBegin(SQL_STATE_FIELD_DESC);
          oprot.writeString(struct.sqlState);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetVendorCode()) {
        oprot.writeFieldBegin(VENDOR_CODE_FIELD_DESC);
        oprot.writeI32(struct.vendorCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FailErrorTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public FailErrorTupleScheme getScheme() {
      return new FailErrorTupleScheme();
    }
  }

  private static class FailErrorTupleScheme extends org.apache.thrift.scheme.TupleScheme<FailError> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FailError struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMessage()) {
        optionals.set(0);
      }
      if (struct.isSetTrace()) {
        optionals.set(1);
      }
      if (struct.isSetSqlState()) {
        optionals.set(2);
      }
      if (struct.isSetVendorCode()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetMessage()) {
        oprot.writeString(struct.message);
      }
      if (struct.isSetTrace()) {
        oprot.writeString(struct.trace);
      }
      if (struct.isSetSqlState()) {
        oprot.writeString(struct.sqlState);
      }
      if (struct.isSetVendorCode()) {
        oprot.writeI32(struct.vendorCode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FailError struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.message = iprot.readString();
        struct.setMessageIsSet(true);
      }
      if (incoming.get(1)) {
        struct.trace = iprot.readString();
        struct.setTraceIsSet(true);
      }
      if (incoming.get(2)) {
        struct.sqlState = iprot.readString();
        struct.setSqlStateIsSet(true);
      }
      if (incoming.get(3)) {
        struct.vendorCode = iprot.readI32();
        struct.setVendorCodeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

