/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.database.jdbc.rt.shared;


/**
 * The kind of a JdbcValue and the field that holds it. The field of the kind may be unset: that means SQL NULL too, like _null.
 * 
 * Temporal values travel as ISO-8601 text in stringValue, written by the toString() of the java.time class and read back with
 * its parse(). The text keeps the full precision (up to nanoseconds) and years outside 0000-9999 (+10000-01-01, -0001-01-01).
 */
public enum JdbcValueType implements org.apache.thrift.TEnum {
  /**
   * intValue: TINYINT, SMALLINT, INTEGER
   */
  _int(0),
  /**
   * stringValue: character types, CLOB, NCLOB, SQLXML, and a value which could not be read as its column type
   */
  _string(1),
  /**
   * boolValue: BOOLEAN, BIT of precision 1
   */
  _bool(2),
  /**
   * longValue: BIGINT
   */
  _long(3),
  /**
   * SQL NULL, no field is set
   */
  _null(4),
  /**
   * doubleValue: REAL, FLOAT, DOUBLE
   */
  _double(5),
  /**
   * stringValue: BigDecimal.toPlainString() of NUMERIC, DECIMAL and unsigned BIGINT
   */
  _decimal(6),
  /**
   * stringValue: LocalDate, for example 2024-02-29
   */
  _date(7),
  /**
   * stringValue: LocalTime (10:15:30.123456), or OffsetTime (10:15:30+02:00) for TIME WITH TIME ZONE
   */
  _time(8),
  /**
   * stringValue: LocalDateTime, for example 2024-02-29T10:15:30.123456
   */
  _timestamp(9),
  /**
   * stringValue: OffsetDateTime, for example 2024-02-29T10:15:30.123456+02:00
   */
  _timestamptz(10),
  /**
   * bytesValue: BINARY, VARBINARY, LONGVARBINARY, BLOB
   */
  _bytes(11),
  /**
   * arrayValue: the elements of an ARRAY, each a JdbcValue of its own kind (an inner array is an _array value)
   */
  _array(12),
  /**
   * stringValue: ResultSet.getString() of a value of any other type; className: the class of ResultSet.getObject()
   */
  _other(13);

  private final int value;

  private JdbcValueType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static JdbcValueType findByValue(int value) { 
    switch (value) {
      case 0:
        return _int;
      case 1:
        return _string;
      case 2:
        return _bool;
      case 3:
        return _long;
      case 4:
        return _null;
      case 5:
        return _double;
      case 6:
        return _decimal;
      case 7:
        return _date;
      case 8:
        return _time;
      case 9:
        return _timestamp;
      case 10:
        return _timestamptz;
      case 11:
        return _bytes;
      case 12:
        return _array;
      case 13:
        return _other;
      default:
        return null;
    }
  }
}
