/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.database.mongo.rt.shared;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class MongoFindResult implements org.apache.thrift.TBase<MongoFindResult, MongoFindResult._Fields>, java.io.Serializable, Cloneable, Comparable<MongoFindResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MongoFindResult");

  private static final org.apache.thrift.protocol.TField DOCUMENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("documents", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField TRUNCATED_FIELD_DESC = new org.apache.thrift.protocol.TField("truncated", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MongoFindResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MongoFindResultTupleSchemeFactory();

  /**
   * DOCUMENT nodes
   */
  public @org.apache.thrift.annotation.Nullable java.util.List<MongoNode> documents; // required
  /**
   * The documents stopped before the limit, as their BSON size reached the response budget of the runtime. The first
   * document is always returned, whatever its size.
   */
  public boolean truncated; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * DOCUMENT nodes
     */
    DOCUMENTS((short)1, "documents"),
    /**
     * The documents stopped before the limit, as their BSON size reached the response budget of the runtime. The first
     * document is always returned, whatever its size.
     */
    TRUNCATED((short)2, "truncated");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DOCUMENTS
          return DOCUMENTS;
        case 2: // TRUNCATED
          return TRUNCATED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TRUNCATED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DOCUMENTS, new org.apache.thrift.meta_data.FieldMetaData("documents", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MongoNode.class))));
    tmpMap.put(_Fields.TRUNCATED, new org.apache.thrift.meta_data.FieldMetaData("truncated", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MongoFindResult.class, metaDataMap);
  }

  public MongoFindResult() {
  }

  public MongoFindResult(
    java.util.List<MongoNode> documents,
    boolean truncated)
  {
    this();
    this.documents = documents;
    this.truncated = truncated;
    setTruncatedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MongoFindResult(MongoFindResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDocuments()) {
      java.util.List<MongoNode> __this__documents = new java.util.ArrayList<MongoNode>(other.documents.size());
      for (MongoNode other_element : other.documents) {
        __this__documents.add(new MongoNode(other_element));
      }
      this.documents = __this__documents;
    }
    this.truncated = other.truncated;
  }

  @Override
  public MongoFindResult deepCopy() {
    return new MongoFindResult(this);
  }

  @Override
  public void clear() {
    this.documents = null;
    setTruncatedIsSet(false);
    this.truncated = false;
  }

  public int getDocumentsSize() {
    return (this.documents == null) ? 0 : this.documents.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<MongoNode> getDocumentsIterator() {
    return (this.documents == null) ? null : this.documents.iterator();
  }

  public void addToDocuments(MongoNode elem) {
    if (this.documents == null) {
      this.documents = new java.util.ArrayList<MongoNode>();
    }
    this.documents.add(elem);
  }

  /**
   * DOCUMENT nodes
   */
  @org.apache.thrift.annotation.Nullable
  public java.util.List<MongoNode> getDocuments() {
    return this.documents;
  }

  /**
   * DOCUMENT nodes
   */
  public MongoFindResult setDocuments(@org.apache.thrift.annotation.Nullable java.util.List<MongoNode> documents) {
    this.documents = documents;
    return this;
  }

  public void unsetDocuments() {
    this.documents = null;
  }

  /** Returns true if field documents is set (has been assigned a value) and false otherwise */
  public boolean isSetDocuments() {
    return this.documents != null;
  }

  public void setDocumentsIsSet(boolean value) {
    if (!value) {
      this.documents = null;
    }
  }

  /**
   * The documents stopped before the limit, as their BSON size reached the response budget of the runtime. The first
   * document is always returned, whatever its size.
   */
  public boolean isTruncated() {
    return this.truncated;
  }

  /**
   * The documents stopped before the limit, as their BSON size reached the response budget of the runtime. The first
   * document is always returned, whatever its size.
   */
  public MongoFindResult setTruncated(boolean truncated) {
    this.truncated = truncated;
    setTruncatedIsSet(true);
    return this;
  }

  public void unsetTruncated() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TRUNCATED_ISSET_ID);
  }

  /** Returns true if field truncated is set (has been assigned a value) and false otherwise */
  public boolean isSetTruncated() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TRUNCATED_ISSET_ID);
  }

  public void setTruncatedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TRUNCATED_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DOCUMENTS:
      if (value == null) {
        unsetDocuments();
      } else {
        setDocuments((java.util.List<MongoNode>)value);
      }
      break;

    case TRUNCATED:
      if (value == null) {
        unsetTruncated();
      } else {
        setTruncated((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DOCUMENTS:
      return getDocuments();

    case TRUNCATED:
      return isTruncated();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DOCUMENTS:
      return isSetDocuments();
    case TRUNCATED:
      return isSetTruncated();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof MongoFindResult)
      return this.equals((MongoFindResult)that);
    return false;
  }

  public boolean equals(MongoFindResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_documents = true && this.isSetDocuments();
    boolean that_present_documents = true && that.isSetDocuments();
    if (this_present_documents || that_present_documents) {
      if (!(this_present_documents && that_present_documents))
        return false;
      if (!this.documents.equals(that.documents))
        return false;
    }

    boolean this_present_truncated = true;
    boolean that_present_truncated = true;
    if (this_present_truncated || that_present_truncated) {
      if (!(this_present_truncated && that_present_truncated))
        return false;
      if (this.truncated != that.truncated)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDocuments()) ? 131071 : 524287);
    if (isSetDocuments())
      hashCode = hashCode * 8191 + documents.hashCode();

    hashCode = hashCode * 8191 + ((truncated) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(MongoFindResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetDocuments(), other.isSetDocuments());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocuments()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.documents, other.documents);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTruncated(), other.isSetTruncated());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTruncated()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.truncated, other.truncated);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MongoFindResult(");
    boolean first = true;

    sb.append("documents:");
    if (this.documents == null) {
      sb.append("null");
    } else {
      sb.append(this.documents);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("truncated:");
    sb.append(this.truncated);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MongoFindResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MongoFindResultStandardScheme getScheme() {
      return new MongoFindResultStandardScheme();
    }
  }

  private static class MongoFindResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<MongoFindResult> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, MongoFindResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DOCUMENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.documents = new java.util.ArrayList<MongoNode>(_list8.size);
                @org.apache.thrift.annotation.Nullable MongoNode _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new MongoNode();
                  _elem9.read(iprot);
                  struct.documents.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setDocumentsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TRUNCATED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.truncated = iprot.readBool();
              struct.setTruncatedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, MongoFindResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.documents != null) {
        oprot.writeFieldBegin(DOCUMENTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.documents.size()));
          for (MongoNode _iter11 : struct.documents)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TRUNCATED_FIELD_DESC);
      oprot.writeBool(struct.truncated);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MongoFindResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MongoFindResultTupleScheme getScheme() {
      return new MongoFindResultTupleScheme();
    }
  }

  private static class MongoFindResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<MongoFindResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MongoFindResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDocuments()) {
        optionals.set(0);
      }
      if (struct.isSetTruncated()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetDocuments()) {
        {
          oprot.writeI32(struct.documents.size());
          for (MongoNode _iter12 : struct.documents)
          {
            _iter12.write(oprot);
          }
        }
      }
      if (struct.isSetTruncated()) {
        oprot.writeBool(struct.truncated);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MongoFindResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.documents = new java.util.ArrayList<MongoNode>(_list13.size);
          @org.apache.thrift.annotation.Nullable MongoNode _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new MongoNode();
            _elem14.read(iprot);
            struct.documents.add(_elem14);
          }
        }
        struct.setDocumentsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.truncated = iprot.readBool();
        struct.setTruncatedIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

