/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.database.mongo.rt.shared;

/**
 * The connection settings of a data source. The generated toString() prints every field, the password included: never log it.
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class MongoConnectSettings implements org.apache.thrift.TBase<MongoConnectSettings, MongoConnectSettings._Fields>, java.io.Serializable, Cloneable, Comparable<MongoConnectSettings> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MongoConnectSettings");

  private static final org.apache.thrift.protocol.TField CONNECTION_STRING_FIELD_DESC = new org.apache.thrift.protocol.TField("connectionString", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField HOST_FIELD_DESC = new org.apache.thrift.protocol.TField("host", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("port", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField LOGIN_FIELD_DESC = new org.apache.thrift.protocol.TField("login", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField PASSWORD_FIELD_DESC = new org.apache.thrift.protocol.TField("password", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField AUTH_SOURCE_FIELD_DESC = new org.apache.thrift.protocol.TField("authSource", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField SERVER_SELECTION_TIMEOUT_MS_FIELD_DESC = new org.apache.thrift.protocol.TField("serverSelectionTimeoutMs", org.apache.thrift.protocol.TType.I32, (short)7);
  private static final org.apache.thrift.protocol.TField CONNECT_TIMEOUT_MS_FIELD_DESC = new org.apache.thrift.protocol.TField("connectTimeoutMs", org.apache.thrift.protocol.TType.I32, (short)8);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MongoConnectSettingsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MongoConnectSettingsTupleSchemeFactory();

  /**
   * A mongodb:// or mongodb+srv:// string without password. When set, host and port are ignored.
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String connectionString; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String host; // required
  public int port; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String login; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String password; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String authSource; // required
  /**
   * connect() applies it only when the connection string sets no serverSelectionTimeoutMS; testConnection() always applies it.
   */
  public int serverSelectionTimeoutMs; // required
  /**
   * Applied only when the connection string sets no connectTimeoutMS.
   */
  public int connectTimeoutMs; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * A mongodb:// or mongodb+srv:// string without password. When set, host and port are ignored.
     */
    CONNECTION_STRING((short)1, "connectionString"),
    HOST((short)2, "host"),
    PORT((short)3, "port"),
    LOGIN((short)4, "login"),
    PASSWORD((short)5, "password"),
    AUTH_SOURCE((short)6, "authSource"),
    /**
     * connect() applies it only when the connection string sets no serverSelectionTimeoutMS; testConnection() always applies it.
     */
    SERVER_SELECTION_TIMEOUT_MS((short)7, "serverSelectionTimeoutMs"),
    /**
     * Applied only when the connection string sets no connectTimeoutMS.
     */
    CONNECT_TIMEOUT_MS((short)8, "connectTimeoutMs");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CONNECTION_STRING
          return CONNECTION_STRING;
        case 2: // HOST
          return HOST;
        case 3: // PORT
          return PORT;
        case 4: // LOGIN
          return LOGIN;
        case 5: // PASSWORD
          return PASSWORD;
        case 6: // AUTH_SOURCE
          return AUTH_SOURCE;
        case 7: // SERVER_SELECTION_TIMEOUT_MS
          return SERVER_SELECTION_TIMEOUT_MS;
        case 8: // CONNECT_TIMEOUT_MS
          return CONNECT_TIMEOUT_MS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PORT_ISSET_ID = 0;
  private static final int __SERVERSELECTIONTIMEOUTMS_ISSET_ID = 1;
  private static final int __CONNECTTIMEOUTMS_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.CONNECTION_STRING,_Fields.LOGIN,_Fields.PASSWORD};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CONNECTION_STRING, new org.apache.thrift.meta_data.FieldMetaData("connectionString", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HOST, new org.apache.thrift.meta_data.FieldMetaData("host", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PORT, new org.apache.thrift.meta_data.FieldMetaData("port", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LOGIN, new org.apache.thrift.meta_data.FieldMetaData("login", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PASSWORD, new org.apache.thrift.meta_data.FieldMetaData("password", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AUTH_SOURCE, new org.apache.thrift.meta_data.FieldMetaData("authSource", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SERVER_SELECTION_TIMEOUT_MS, new org.apache.thrift.meta_data.FieldMetaData("serverSelectionTimeoutMs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CONNECT_TIMEOUT_MS, new org.apache.thrift.meta_data.FieldMetaData("connectTimeoutMs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MongoConnectSettings.class, metaDataMap);
  }

  public MongoConnectSettings() {
  }

  public MongoConnectSettings(
    java.lang.String host,
    int port,
    java.lang.String authSource,
    int serverSelectionTimeoutMs,
    int connectTimeoutMs)
  {
    this();
    this.host = host;
    this.port = port;
    setPortIsSet(true);
    this.authSource = authSource;
    this.serverSelectionTimeoutMs = serverSelectionTimeoutMs;
    setServerSelectionTimeoutMsIsSet(true);
    this.connectTimeoutMs = connectTimeoutMs;
    setConnectTimeoutMsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MongoConnectSettings(MongoConnectSettings other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetConnectionString()) {
      this.connectionString = other.connectionString;
    }
    if (other.isSetHost()) {
      this.host = other.host;
    }
    this.port = other.port;
    if (other.isSetLogin()) {
      this.login = other.login;
    }
    if (other.isSetPassword()) {
      this.password = other.password;
    }
    if (other.isSetAuthSource()) {
      this.authSource = other.authSource;
    }
    this.serverSelectionTimeoutMs = other.serverSelectionTimeoutMs;
    this.connectTimeoutMs = other.connectTimeoutMs;
  }

  @Override
  public MongoConnectSettings deepCopy() {
    return new MongoConnectSettings(this);
  }

  @Override
  public void clear() {
    this.connectionString = null;
    this.host = null;
    setPortIsSet(false);
    this.port = 0;
    this.login = null;
    this.password = null;
    this.authSource = null;
    setServerSelectionTimeoutMsIsSet(false);
    this.serverSelectionTimeoutMs = 0;
    setConnectTimeoutMsIsSet(false);
    this.connectTimeoutMs = 0;
  }

  /**
   * A mongodb:// or mongodb+srv:// string without password. When set, host and port are ignored.
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getConnectionString() {
    return this.connectionString;
  }

  /**
   * A mongodb:// or mongodb+srv:// string without password. When set, host and port are ignored.
   */
  public MongoConnectSettings setConnectionString(@org.apache.thrift.annotation.Nullable java.lang.String connectionString) {
    this.connectionString = connectionString;
    return this;
  }

  public void unsetConnectionString() {
    this.connectionString = null;
  }

  /** Returns true if field connectionString is set (has been assigned a value) and false otherwise */
  public boolean isSetConnectionString() {
    return this.connectionString != null;
  }

  public void setConnectionStringIsSet(boolean value) {
    if (!value) {
      this.connectionString = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getHost() {
    return this.host;
  }

  public MongoConnectSettings setHost(@org.apache.thrift.annotation.Nullable java.lang.String host) {
    this.host = host;
    return this;
  }

  public void unsetHost() {
    this.host = null;
  }

  /** Returns true if field host is set (has been assigned a value) and false otherwise */
  public boolean isSetHost() {
    return this.host != null;
  }

  public void setHostIsSet(boolean value) {
    if (!value) {
      this.host = null;
    }
  }

  public int getPort() {
    return this.port;
  }

  public MongoConnectSettings setPort(int port) {
    this.port = port;
    setPortIsSet(true);
    return this;
  }

  public void unsetPort() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  /** Returns true if field port is set (has been assigned a value) and false otherwise */
  public boolean isSetPort() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  public void setPortIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PORT_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getLogin() {
    return this.login;
  }

  public MongoConnectSettings setLogin(@org.apache.thrift.annotation.Nullable java.lang.String login) {
    this.login = login;
    return this;
  }

  public void unsetLogin() {
    this.login = null;
  }

  /** Returns true if field login is set (has been assigned a value) and false otherwise */
  public boolean isSetLogin() {
    return this.login != null;
  }

  public void setLoginIsSet(boolean value) {
    if (!value) {
      this.login = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPassword() {
    return this.password;
  }

  public MongoConnectSettings setPassword(@org.apache.thrift.annotation.Nullable java.lang.String password) {
    this.password = password;
    return this;
  }

  public void unsetPassword() {
    this.password = null;
  }

  /** Returns true if field password is set (has been assigned a value) and false otherwise */
  public boolean isSetPassword() {
    return this.password != null;
  }

  public void setPasswordIsSet(boolean value) {
    if (!value) {
      this.password = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAuthSource() {
    return this.authSource;
  }

  public MongoConnectSettings setAuthSource(@org.apache.thrift.annotation.Nullable java.lang.String authSource) {
    this.authSource = authSource;
    return this;
  }

  public void unsetAuthSource() {
    this.authSource = null;
  }

  /** Returns true if field authSource is set (has been assigned a value) and false otherwise */
  public boolean isSetAuthSource() {
    return this.authSource != null;
  }

  public void setAuthSourceIsSet(boolean value) {
    if (!value) {
      this.authSource = null;
    }
  }

  /**
   * connect() applies it only when the connection string sets no serverSelectionTimeoutMS; testConnection() always applies it.
   */
  public int getServerSelectionTimeoutMs() {
    return this.serverSelectionTimeoutMs;
  }

  /**
   * connect() applies it only when the connection string sets no serverSelectionTimeoutMS; testConnection() always applies it.
   */
  public MongoConnectSettings setServerSelectionTimeoutMs(int serverSelectionTimeoutMs) {
    this.serverSelectionTimeoutMs = serverSelectionTimeoutMs;
    setServerSelectionTimeoutMsIsSet(true);
    return this;
  }

  public void unsetServerSelectionTimeoutMs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SERVERSELECTIONTIMEOUTMS_ISSET_ID);
  }

  /** Returns true if field serverSelectionTimeoutMs is set (has been assigned a value) and false otherwise */
  public boolean isSetServerSelectionTimeoutMs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SERVERSELECTIONTIMEOUTMS_ISSET_ID);
  }

  public void setServerSelectionTimeoutMsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SERVERSELECTIONTIMEOUTMS_ISSET_ID, value);
  }

  /**
   * Applied only when the connection string sets no connectTimeoutMS.
   */
  public int getConnectTimeoutMs() {
    return this.connectTimeoutMs;
  }

  /**
   * Applied only when the connection string sets no connectTimeoutMS.
   */
  public MongoConnectSettings setConnectTimeoutMs(int connectTimeoutMs) {
    this.connectTimeoutMs = connectTimeoutMs;
    setConnectTimeoutMsIsSet(true);
    return this;
  }

  public void unsetConnectTimeoutMs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CONNECTTIMEOUTMS_ISSET_ID);
  }

  /** Returns true if field connectTimeoutMs is set (has been assigned a value) and false otherwise */
  public boolean isSetConnectTimeoutMs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CONNECTTIMEOUTMS_ISSET_ID);
  }

  public void setConnectTimeoutMsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CONNECTTIMEOUTMS_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CONNECTION_STRING:
      if (value == null) {
        unsetConnectionString();
      } else {
        setConnectionString((java.lang.String)value);
      }
      break;

    case HOST:
      if (value == null) {
        unsetHost();
      } else {
        setHost((java.lang.String)value);
      }
      break;

    case PORT:
      if (value == null) {
        unsetPort();
      } else {
        setPort((java.lang.Integer)value);
      }
      break;

    case LOGIN:
      if (value == null) {
        unsetLogin();
      } else {
        setLogin((java.lang.String)value);
      }
      break;

    case PASSWORD:
      if (value == null) {
        unsetPassword();
      } else {
        setPassword((java.lang.String)value);
      }
      break;

    case AUTH_SOURCE:
      if (value == null) {
        unsetAuthSource();
      } else {
        setAuthSource((java.lang.String)value);
      }
      break;

    case SERVER_SELECTION_TIMEOUT_MS:
      if (value == null) {
        unsetServerSelectionTimeoutMs();
      } else {
        setServerSelectionTimeoutMs((java.lang.Integer)value);
      }
      break;

    case CONNECT_TIMEOUT_MS:
      if (value == null) {
        unsetConnectTimeoutMs();
      } else {
        setConnectTimeoutMs((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CONNECTION_STRING:
      return getConnectionString();

    case HOST:
      return getHost();

    case PORT:
      return getPort();

    case LOGIN:
      return getLogin();

    case PASSWORD:
      return getPassword();

    case AUTH_SOURCE:
      return getAuthSource();

    case SERVER_SELECTION_TIMEOUT_MS:
      return getServerSelectionTimeoutMs();

    case CONNECT_TIMEOUT_MS:
      return getConnectTimeoutMs();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CONNECTION_STRING:
      return isSetConnectionString();
    case HOST:
      return isSetHost();
    case PORT:
      return isSetPort();
    case LOGIN:
      return isSetLogin();
    case PASSWORD:
      return isSetPassword();
    case AUTH_SOURCE:
      return isSetAuthSource();
    case SERVER_SELECTION_TIMEOUT_MS:
      return isSetServerSelectionTimeoutMs();
    case CONNECT_TIMEOUT_MS:
      return isSetConnectTimeoutMs();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof MongoConnectSettings)
      return this.equals((MongoConnectSettings)that);
    return false;
  }

  public boolean equals(MongoConnectSettings that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_connectionString = true && this.isSetConnectionString();
    boolean that_present_connectionString = true && that.isSetConnectionString();
    if (this_present_connectionString || that_present_connectionString) {
      if (!(this_present_connectionString && that_present_connectionString))
        return false;
      if (!this.connectionString.equals(that.connectionString))
        return false;
    }

    boolean this_present_host = true && this.isSetHost();
    boolean that_present_host = true && that.isSetHost();
    if (this_present_host || that_present_host) {
      if (!(this_present_host && that_present_host))
        return false;
      if (!this.host.equals(that.host))
        return false;
    }

    boolean this_present_port = true;
    boolean that_present_port = true;
    if (this_present_port || that_present_port) {
      if (!(this_present_port && that_present_port))
        return false;
      if (this.port != that.port)
        return false;
    }

    boolean this_present_login = true && this.isSetLogin();
    boolean that_present_login = true && that.isSetLogin();
    if (this_present_login || that_present_login) {
      if (!(this_present_login && that_present_login))
        return false;
      if (!this.login.equals(that.login))
        return false;
    }

    boolean this_present_password = true && this.isSetPassword();
    boolean that_present_password = true && that.isSetPassword();
    if (this_present_password || that_present_password) {
      if (!(this_present_password && that_present_password))
        return false;
      if (!this.password.equals(that.password))
        return false;
    }

    boolean this_present_authSource = true && this.isSetAuthSource();
    boolean that_present_authSource = true && that.isSetAuthSource();
    if (this_present_authSource || that_present_authSource) {
      if (!(this_present_authSource && that_present_authSource))
        return false;
      if (!this.authSource.equals(that.authSource))
        return false;
    }

    boolean this_present_serverSelectionTimeoutMs = true;
    boolean that_present_serverSelectionTimeoutMs = true;
    if (this_present_serverSelectionTimeoutMs || that_present_serverSelectionTimeoutMs) {
      if (!(this_present_serverSelectionTimeoutMs && that_present_serverSelectionTimeoutMs))
        return false;
      if (this.serverSelectionTimeoutMs != that.serverSelectionTimeoutMs)
        return false;
    }

    boolean this_present_connectTimeoutMs = true;
    boolean that_present_connectTimeoutMs = true;
    if (this_present_connectTimeoutMs || that_present_connectTimeoutMs) {
      if (!(this_present_connectTimeoutMs && that_present_connectTimeoutMs))
        return false;
      if (this.connectTimeoutMs != that.connectTimeoutMs)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetConnectionString()) ? 131071 : 524287);
    if (isSetConnectionString())
      hashCode = hashCode * 8191 + connectionString.hashCode();

    hashCode = hashCode * 8191 + ((isSetHost()) ? 131071 : 524287);
    if (isSetHost())
      hashCode = hashCode * 8191 + host.hashCode();

    hashCode = hashCode * 8191 + port;

    hashCode = hashCode * 8191 + ((isSetLogin()) ? 131071 : 524287);
    if (isSetLogin())
      hashCode = hashCode * 8191 + login.hashCode();

    hashCode = hashCode * 8191 + ((isSetPassword()) ? 131071 : 524287);
    if (isSetPassword())
      hashCode = hashCode * 8191 + password.hashCode();

    hashCode = hashCode * 8191 + ((isSetAuthSource()) ? 131071 : 524287);
    if (isSetAuthSource())
      hashCode = hashCode * 8191 + authSource.hashCode();

    hashCode = hashCode * 8191 + serverSelectionTimeoutMs;

    hashCode = hashCode * 8191 + connectTimeoutMs;

    return hashCode;
  }

  @Override
  public int compareTo(MongoConnectSettings other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetConnectionString(), other.isSetConnectionString());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConnectionString()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.connectionString, other.connectionString);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetHost(), other.isSetHost());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHost()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.host, other.host);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPort(), other.isSetPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.port, other.port);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLogin(), other.isSetLogin());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLogin()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.login, other.login);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPassword(), other.isSetPassword());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPassword()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.password, other.password);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAuthSource(), other.isSetAuthSource());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAuthSource()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.authSource, other.authSource);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetServerSelectionTimeoutMs(), other.isSetServerSelectionTimeoutMs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetServerSelectionTimeoutMs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.serverSelectionTimeoutMs, other.serverSelectionTimeoutMs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetConnectTimeoutMs(), other.isSetConnectTimeoutMs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConnectTimeoutMs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.connectTimeoutMs, other.connectTimeoutMs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MongoConnectSettings(");
    boolean first = true;

    if (isSetConnectionString()) {
      sb.append("connectionString:");
      if (this.connectionString == null) {
        sb.append("null");
      } else {
        sb.append(this.connectionString);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("host:");
    if (this.host == null) {
      sb.append("null");
    } else {
      sb.append(this.host);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("port:");
    sb.append(this.port);
    first = false;
    if (isSetLogin()) {
      if (!first) sb.append(", ");
      sb.append("login:");
      if (this.login == null) {
        sb.append("null");
      } else {
        sb.append(this.login);
      }
      first = false;
    }
    if (isSetPassword()) {
      if (!first) sb.append(", ");
      sb.append("password:");
      if (this.password == null) {
        sb.append("null");
      } else {
        sb.append(this.password);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("authSource:");
    if (this.authSource == null) {
      sb.append("null");
    } else {
      sb.append(this.authSource);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("serverSelectionTimeoutMs:");
    sb.append(this.serverSelectionTimeoutMs);
    first = false;
    if (!first) sb.append(", ");
    sb.append("connectTimeoutMs:");
    sb.append(this.connectTimeoutMs);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MongoConnectSettingsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MongoConnectSettingsStandardScheme getScheme() {
      return new MongoConnectSettingsStandardScheme();
    }
  }

  private static class MongoConnectSettingsStandardScheme extends org.apache.thrift.scheme.StandardScheme<MongoConnectSettings> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, MongoConnectSettings struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CONNECTION_STRING
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.connectionString = iprot.readString();
              struct.setConnectionStringIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // HOST
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.host = iprot.readString();
              struct.setHostIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.port = iprot.readI32();
              struct.setPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LOGIN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.login = iprot.readString();
              struct.setLoginIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PASSWORD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.password = iprot.readString();
              struct.setPasswordIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // AUTH_SOURCE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.authSource = iprot.readString();
              struct.setAuthSourceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // SERVER_SELECTION_TIMEOUT_MS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.serverSelectionTimeoutMs = iprot.readI32();
              struct.setServerSelectionTimeoutMsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // CONNECT_TIMEOUT_MS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.connectTimeoutMs = iprot.readI32();
              struct.setConnectTimeoutMsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, MongoConnectSettings struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.connectionString != null) {
        if (struct.isSetConnectionString()) {
          oprot.writeFieldBegin(CONNECTION_STRING_FIELD_DESC);
          oprot.writeString(struct.connectionString);
          oprot.writeFieldEnd();
        }
      }
      if (struct.host != null) {
        oprot.writeFieldBegin(HOST_FIELD_DESC);
        oprot.writeString(struct.host);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PORT_FIELD_DESC);
      oprot.writeI32(struct.port);
      oprot.writeFieldEnd();
      if (struct.login != null) {
        if (struct.isSetLogin()) {
          oprot.writeFieldBegin(LOGIN_FIELD_DESC);
          oprot.writeString(struct.login);
          oprot.writeFieldEnd();
        }
      }
      if (struct.password != null) {
        if (struct.isSetPassword()) {
          oprot.writeFieldBegin(PASSWORD_FIELD_DESC);
          oprot.writeString(struct.password);
          oprot.writeFieldEnd();
        }
      }
      if (struct.authSource != null) {
        oprot.writeFieldBegin(AUTH_SOURCE_FIELD_DESC);
        oprot.writeString(struct.authSource);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SERVER_SELECTION_TIMEOUT_MS_FIELD_DESC);
      oprot.writeI32(struct.serverSelectionTimeoutMs);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CONNECT_TIMEOUT_MS_FIELD_DESC);
      oprot.writeI32(struct.connectTimeoutMs);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MongoConnectSettingsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MongoConnectSettingsTupleScheme getScheme() {
      return new MongoConnectSettingsTupleScheme();
    }
  }

  private static class MongoConnectSettingsTupleScheme extends org.apache.thrift.scheme.TupleScheme<MongoConnectSettings> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MongoConnectSettings struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetConnectionString()) {
        optionals.set(0);
      }
      if (struct.isSetHost()) {
        optionals.set(1);
      }
      if (struct.isSetPort()) {
        optionals.set(2);
      }
      if (struct.isSetLogin()) {
        optionals.set(3);
      }
      if (struct.isSetPassword()) {
        optionals.set(4);
      }
      if (struct.isSetAuthSource()) {
        optionals.set(5);
      }
      if (struct.isSetServerSelectionTimeoutMs()) {
        optionals.set(6);
      }
      if (struct.isSetConnectTimeoutMs()) {
        optionals.set(7);
      }
      oprot.writeBitSet(optionals, 8);
      if (struct.isSetConnectionString()) {
        oprot.writeString(struct.connectionString);
      }
      if (struct.isSetHost()) {
        oprot.writeString(struct.host);
      }
      if (struct.isSetPort()) {
        oprot.writeI32(struct.port);
      }
      if (struct.isSetLogin()) {
        oprot.writeString(struct.login);
      }
      if (struct.isSetPassword()) {
        oprot.writeString(struct.password);
      }
      if (struct.isSetAuthSource()) {
        oprot.writeString(struct.authSource);
      }
      if (struct.isSetServerSelectionTimeoutMs()) {
        oprot.writeI32(struct.serverSelectionTimeoutMs);
      }
      if (struct.isSetConnectTimeoutMs()) {
        oprot.writeI32(struct.connectTimeoutMs);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MongoConnectSettings struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(8);
      if (incoming.get(0)) {
        struct.connectionString = iprot.readString();
        struct.setConnectionStringIsSet(true);
      }
      if (incoming.get(1)) {
        struct.host = iprot.readString();
        struct.setHostIsSet(true);
      }
      if (incoming.get(2)) {
        struct.port = iprot.readI32();
        struct.setPortIsSet(true);
      }
      if (incoming.get(3)) {
        struct.login = iprot.readString();
        struct.setLoginIsSet(true);
      }
      if (incoming.get(4)) {
        struct.password = iprot.readString();
        struct.setPasswordIsSet(true);
      }
      if (incoming.get(5)) {
        struct.authSource = iprot.readString();
        struct.setAuthSourceIsSet(true);
      }
      if (incoming.get(6)) {
        struct.serverSelectionTimeoutMs = iprot.readI32();
        struct.setServerSelectionTimeoutMsIsSet(true);
      }
      if (incoming.get(7)) {
        struct.connectTimeoutMs = iprot.readI32();
        struct.setConnectTimeoutMsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

