/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.database.mongo.rt.shared;


public enum MongoNodeKind implements org.apache.thrift.TEnum {
  /**
   * Never inside a document - a missing field is simply absent. Reserved for positional cell lists.
   */
  MISSING(0),
  NULL(1),
  UNDEFINED(2),
  BOOL(3),
  INT32(4),
  INT64(5),
  DOUBLE(6),
  DECIMAL128(7),
  STRING(8),
  DATE(9),
  TIMESTAMP(10),
  OBJECT_ID(11),
  UUID(12),
  BINARY(13),
  DOCUMENT(14),
  ARRAY(15),
  OTHER(16);

  private final int value;

  private MongoNodeKind(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static MongoNodeKind findByValue(int value) { 
    switch (value) {
      case 0:
        return MISSING;
      case 1:
        return NULL;
      case 2:
        return UNDEFINED;
      case 3:
        return BOOL;
      case 4:
        return INT32;
      case 5:
        return INT64;
      case 6:
        return DOUBLE;
      case 7:
        return DECIMAL128;
      case 8:
        return STRING;
      case 9:
        return DATE;
      case 10:
        return TIMESTAMP;
      case 11:
        return OBJECT_ID;
      case 12:
        return UUID;
      case 13:
        return BINARY;
      case 14:
        return DOCUMENT;
      case 15:
        return ARRAY;
      case 16:
        return OTHER;
      default:
        return null;
    }
  }
}
