/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.database.mongo.rt.shared;

/**
 * A BSON value as a tree node.
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class MongoNode implements org.apache.thrift.TBase<MongoNode, MongoNode._Fields>, java.io.Serializable, Cloneable, Comparable<MongoNode> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MongoNode");

  private static final org.apache.thrift.protocol.TField KIND_FIELD_DESC = new org.apache.thrift.protocol.TField("kind", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField BOOL_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("boolValue", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField INT_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("intValue", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField LONG_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("longValue", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField DOUBLE_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("doubleValue", org.apache.thrift.protocol.TType.DOUBLE, (short)6);
  private static final org.apache.thrift.protocol.TField TEXT_FIELD_DESC = new org.apache.thrift.protocol.TField("text", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField BYTES_FIELD_DESC = new org.apache.thrift.protocol.TField("bytes", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField BINARY_SUBTYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("binarySubtype", org.apache.thrift.protocol.TType.BYTE, (short)9);
  private static final org.apache.thrift.protocol.TField TYPE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("typeName", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField CHILDREN_FIELD_DESC = new org.apache.thrift.protocol.TField("children", org.apache.thrift.protocol.TType.LIST, (short)11);
  private static final org.apache.thrift.protocol.TField OPTIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("options", org.apache.thrift.protocol.TType.STRING, (short)12);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new MongoNodeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new MongoNodeTupleSchemeFactory();

  /**
   * 
   * @see MongoNodeKind
   */
  public @org.apache.thrift.annotation.Nullable MongoNodeKind kind; // required
  /**
   * The field name when the parent is a DOCUMENT. Unset for array items and for a root.
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String name; // optional
  /**
   * BOOL
   */
  public boolean boolValue; // optional
  /**
   * INT32
   */
  public int intValue; // optional
  /**
   * INT64; DATE: milliseconds since the epoch; TIMESTAMP: seconds << 32 | increment
   */
  public long longValue; // optional
  /**
   * DOUBLE
   */
  public double doubleValue; // optional
  /**
   * STRING; DECIMAL128: Decimal128.toString(), also NaN, Infinity, -Infinity, -0; OBJECT_ID: 24 hex digits;
   * UUID: the canonical text; OTHER: see typeName
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String text; // optional
  /**
   * BINARY
   */
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer bytes; // optional
  /**
   * BINARY
   */
  public byte binarySubtype; // optional
  /**
   * OTHER: the $type alias, and what text holds for it:
   * regex - the pattern, its flags are in options (shown as /pattern/options);
   * javascript - the code;
   * javascriptWithScope - the code, the scope is in children;
   * symbol - the symbol;
   * dbPointer - the display text DBPointer("namespace", hex);
   * minKey, maxKey - MinKey, MaxKey;
   * a type a newer driver adds - its lower case BSON type name, text is the display text
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String typeName; // optional
  /**
   * DOCUMENT: the fields in document order, each with its name. ARRAY: the items. OTHER javascriptWithScope: the fields of
   * the scope document, each with its name
   */
  public @org.apache.thrift.annotation.Nullable java.util.List<MongoNode> children; // optional
  /**
   * OTHER regex: the flags, for example "im"; empty when there are none
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String options; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see MongoNodeKind
     */
    KIND((short)1, "kind"),
    /**
     * The field name when the parent is a DOCUMENT. Unset for array items and for a root.
     */
    NAME((short)2, "name"),
    /**
     * BOOL
     */
    BOOL_VALUE((short)3, "boolValue"),
    /**
     * INT32
     */
    INT_VALUE((short)4, "intValue"),
    /**
     * INT64; DATE: milliseconds since the epoch; TIMESTAMP: seconds << 32 | increment
     */
    LONG_VALUE((short)5, "longValue"),
    /**
     * DOUBLE
     */
    DOUBLE_VALUE((short)6, "doubleValue"),
    /**
     * STRING; DECIMAL128: Decimal128.toString(), also NaN, Infinity, -Infinity, -0; OBJECT_ID: 24 hex digits;
     * UUID: the canonical text; OTHER: see typeName
     */
    TEXT((short)7, "text"),
    /**
     * BINARY
     */
    BYTES((short)8, "bytes"),
    /**
     * BINARY
     */
    BINARY_SUBTYPE((short)9, "binarySubtype"),
    /**
     * OTHER: the $type alias, and what text holds for it:
     * regex - the pattern, its flags are in options (shown as /pattern/options);
     * javascript - the code;
     * javascriptWithScope - the code, the scope is in children;
     * symbol - the symbol;
     * dbPointer - the display text DBPointer("namespace", hex);
     * minKey, maxKey - MinKey, MaxKey;
     * a type a newer driver adds - its lower case BSON type name, text is the display text
     */
    TYPE_NAME((short)10, "typeName"),
    /**
     * DOCUMENT: the fields in document order, each with its name. ARRAY: the items. OTHER javascriptWithScope: the fields of
     * the scope document, each with its name
     */
    CHILDREN((short)11, "children"),
    /**
     * OTHER regex: the flags, for example "im"; empty when there are none
     */
    OPTIONS((short)12, "options");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KIND
          return KIND;
        case 2: // NAME
          return NAME;
        case 3: // BOOL_VALUE
          return BOOL_VALUE;
        case 4: // INT_VALUE
          return INT_VALUE;
        case 5: // LONG_VALUE
          return LONG_VALUE;
        case 6: // DOUBLE_VALUE
          return DOUBLE_VALUE;
        case 7: // TEXT
          return TEXT;
        case 8: // BYTES
          return BYTES;
        case 9: // BINARY_SUBTYPE
          return BINARY_SUBTYPE;
        case 10: // TYPE_NAME
          return TYPE_NAME;
        case 11: // CHILDREN
          return CHILDREN;
        case 12: // OPTIONS
          return OPTIONS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __BOOLVALUE_ISSET_ID = 0;
  private static final int __INTVALUE_ISSET_ID = 1;
  private static final int __LONGVALUE_ISSET_ID = 2;
  private static final int __DOUBLEVALUE_ISSET_ID = 3;
  private static final int __BINARYSUBTYPE_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.NAME,_Fields.BOOL_VALUE,_Fields.INT_VALUE,_Fields.LONG_VALUE,_Fields.DOUBLE_VALUE,_Fields.TEXT,_Fields.BYTES,_Fields.BINARY_SUBTYPE,_Fields.TYPE_NAME,_Fields.CHILDREN,_Fields.OPTIONS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KIND, new org.apache.thrift.meta_data.FieldMetaData("kind", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, MongoNodeKind.class)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BOOL_VALUE, new org.apache.thrift.meta_data.FieldMetaData("boolValue", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.INT_VALUE, new org.apache.thrift.meta_data.FieldMetaData("intValue", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LONG_VALUE, new org.apache.thrift.meta_data.FieldMetaData("longValue", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.DOUBLE_VALUE, new org.apache.thrift.meta_data.FieldMetaData("doubleValue", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.TEXT, new org.apache.thrift.meta_data.FieldMetaData("text", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BYTES, new org.apache.thrift.meta_data.FieldMetaData("bytes", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.BINARY_SUBTYPE, new org.apache.thrift.meta_data.FieldMetaData("binarySubtype", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.TYPE_NAME, new org.apache.thrift.meta_data.FieldMetaData("typeName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CHILDREN, new org.apache.thrift.meta_data.FieldMetaData("children", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MongoNode.class))));
    tmpMap.put(_Fields.OPTIONS, new org.apache.thrift.meta_data.FieldMetaData("options", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MongoNode.class, metaDataMap);
  }

  public MongoNode() {
  }

  public MongoNode(
    MongoNodeKind kind)
  {
    this();
    this.kind = kind;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MongoNode(MongoNode other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetKind()) {
      this.kind = other.kind;
    }
    if (other.isSetName()) {
      this.name = other.name;
    }
    this.boolValue = other.boolValue;
    this.intValue = other.intValue;
    this.longValue = other.longValue;
    this.doubleValue = other.doubleValue;
    if (other.isSetText()) {
      this.text = other.text;
    }
    if (other.isSetBytes()) {
      this.bytes = org.apache.thrift.TBaseHelper.copyBinary(other.bytes);
    }
    this.binarySubtype = other.binarySubtype;
    if (other.isSetTypeName()) {
      this.typeName = other.typeName;
    }
    if (other.isSetChildren()) {
      java.util.List<MongoNode> __this__children = new java.util.ArrayList<MongoNode>(other.children.size());
      for (MongoNode other_element : other.children) {
        __this__children.add(new MongoNode(other_element));
      }
      this.children = __this__children;
    }
    if (other.isSetOptions()) {
      this.options = other.options;
    }
  }

  @Override
  public MongoNode deepCopy() {
    return new MongoNode(this);
  }

  @Override
  public void clear() {
    this.kind = null;
    this.name = null;
    setBoolValueIsSet(false);
    this.boolValue = false;
    setIntValueIsSet(false);
    this.intValue = 0;
    setLongValueIsSet(false);
    this.longValue = 0;
    setDoubleValueIsSet(false);
    this.doubleValue = 0.0;
    this.text = null;
    this.bytes = null;
    setBinarySubtypeIsSet(false);
    this.binarySubtype = 0;
    this.typeName = null;
    this.children = null;
    this.options = null;
  }

  /**
   * 
   * @see MongoNodeKind
   */
  @org.apache.thrift.annotation.Nullable
  public MongoNodeKind getKind() {
    return this.kind;
  }

  /**
   * 
   * @see MongoNodeKind
   */
  public MongoNode setKind(@org.apache.thrift.annotation.Nullable MongoNodeKind kind) {
    this.kind = kind;
    return this;
  }

  public void unsetKind() {
    this.kind = null;
  }

  /** Returns true if field kind is set (has been assigned a value) and false otherwise */
  public boolean isSetKind() {
    return this.kind != null;
  }

  public void setKindIsSet(boolean value) {
    if (!value) {
      this.kind = null;
    }
  }

  /**
   * The field name when the parent is a DOCUMENT. Unset for array items and for a root.
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getName() {
    return this.name;
  }

  /**
   * The field name when the parent is a DOCUMENT. Unset for array items and for a root.
   */
  public MongoNode setName(@org.apache.thrift.annotation.Nullable java.lang.String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  /**
   * BOOL
   */
  public boolean isBoolValue() {
    return this.boolValue;
  }

  /**
   * BOOL
   */
  public MongoNode setBoolValue(boolean boolValue) {
    this.boolValue = boolValue;
    setBoolValueIsSet(true);
    return this;
  }

  public void unsetBoolValue() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BOOLVALUE_ISSET_ID);
  }

  /** Returns true if field boolValue is set (has been assigned a value) and false otherwise */
  public boolean isSetBoolValue() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BOOLVALUE_ISSET_ID);
  }

  public void setBoolValueIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BOOLVALUE_ISSET_ID, value);
  }

  /**
   * INT32
   */
  public int getIntValue() {
    return this.intValue;
  }

  /**
   * INT32
   */
  public MongoNode setIntValue(int intValue) {
    this.intValue = intValue;
    setIntValueIsSet(true);
    return this;
  }

  public void unsetIntValue() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __INTVALUE_ISSET_ID);
  }

  /** Returns true if field intValue is set (has been assigned a value) and false otherwise */
  public boolean isSetIntValue() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __INTVALUE_ISSET_ID);
  }

  public void setIntValueIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __INTVALUE_ISSET_ID, value);
  }

  /**
   * INT64; DATE: milliseconds since the epoch; TIMESTAMP: seconds << 32 | increment
   */
  public long getLongValue() {
    return this.longValue;
  }

  /**
   * INT64; DATE: milliseconds since the epoch; TIMESTAMP: seconds << 32 | increment
   */
  public MongoNode setLongValue(long longValue) {
    this.longValue = longValue;
    setLongValueIsSet(true);
    return this;
  }

  public void unsetLongValue() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LONGVALUE_ISSET_ID);
  }

  /** Returns true if field longValue is set (has been assigned a value) and false otherwise */
  public boolean isSetLongValue() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LONGVALUE_ISSET_ID);
  }

  public void setLongValueIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LONGVALUE_ISSET_ID, value);
  }

  /**
   * DOUBLE
   */
  public double getDoubleValue() {
    return this.doubleValue;
  }

  /**
   * DOUBLE
   */
  public MongoNode setDoubleValue(double doubleValue) {
    this.doubleValue = doubleValue;
    setDoubleValueIsSet(true);
    return this;
  }

  public void unsetDoubleValue() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DOUBLEVALUE_ISSET_ID);
  }

  /** Returns true if field doubleValue is set (has been assigned a value) and false otherwise */
  public boolean isSetDoubleValue() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DOUBLEVALUE_ISSET_ID);
  }

  public void setDoubleValueIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DOUBLEVALUE_ISSET_ID, value);
  }

  /**
   * STRING; DECIMAL128: Decimal128.toString(), also NaN, Infinity, -Infinity, -0; OBJECT_ID: 24 hex digits;
   * UUID: the canonical text; OTHER: see typeName
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getText() {
    return this.text;
  }

  /**
   * STRING; DECIMAL128: Decimal128.toString(), also NaN, Infinity, -Infinity, -0; OBJECT_ID: 24 hex digits;
   * UUID: the canonical text; OTHER: see typeName
   */
  public MongoNode setText(@org.apache.thrift.annotation.Nullable java.lang.String text) {
    this.text = text;
    return this;
  }

  public void unsetText() {
    this.text = null;
  }

  /** Returns true if field text is set (has been assigned a value) and false otherwise */
  public boolean isSetText() {
    return this.text != null;
  }

  public void setTextIsSet(boolean value) {
    if (!value) {
      this.text = null;
    }
  }

  /**
   * BINARY
   */
  public byte[] getBytes() {
    setBytes(org.apache.thrift.TBaseHelper.rightSize(bytes));
    return bytes == null ? null : bytes.array();
  }

  public java.nio.ByteBuffer bufferForBytes() {
    return org.apache.thrift.TBaseHelper.copyBinary(bytes);
  }

  /**
   * BINARY
   */
  public MongoNode setBytes(byte[] bytes) {
    this.bytes = bytes == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(bytes.clone());
    return this;
  }

  public MongoNode setBytes(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer bytes) {
    this.bytes = org.apache.thrift.TBaseHelper.copyBinary(bytes);
    return this;
  }

  public void unsetBytes() {
    this.bytes = null;
  }

  /** Returns true if field bytes is set (has been assigned a value) and false otherwise */
  public boolean isSetBytes() {
    return this.bytes != null;
  }

  public void setBytesIsSet(boolean value) {
    if (!value) {
      this.bytes = null;
    }
  }

  /**
   * BINARY
   */
  public byte getBinarySubtype() {
    return this.binarySubtype;
  }

  /**
   * BINARY
   */
  public MongoNode setBinarySubtype(byte binarySubtype) {
    this.binarySubtype = binarySubtype;
    setBinarySubtypeIsSet(true);
    return this;
  }

  public void unsetBinarySubtype() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BINARYSUBTYPE_ISSET_ID);
  }

  /** Returns true if field binarySubtype is set (has been assigned a value) and false otherwise */
  public boolean isSetBinarySubtype() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BINARYSUBTYPE_ISSET_ID);
  }

  public void setBinarySubtypeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BINARYSUBTYPE_ISSET_ID, value);
  }

  /**
   * OTHER: the $type alias, and what text holds for it:
   * regex - the pattern, its flags are in options (shown as /pattern/options);
   * javascript - the code;
   * javascriptWithScope - the code, the scope is in children;
   * symbol - the symbol;
   * dbPointer - the display text DBPointer("namespace", hex);
   * minKey, maxKey - MinKey, MaxKey;
   * a type a newer driver adds - its lower case BSON type name, text is the display text
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTypeName() {
    return this.typeName;
  }

  /**
   * OTHER: the $type alias, and what text holds for it:
   * regex - the pattern, its flags are in options (shown as /pattern/options);
   * javascript - the code;
   * javascriptWithScope - the code, the scope is in children;
   * symbol - the symbol;
   * dbPointer - the display text DBPointer("namespace", hex);
   * minKey, maxKey - MinKey, MaxKey;
   * a type a newer driver adds - its lower case BSON type name, text is the display text
   */
  public MongoNode setTypeName(@org.apache.thrift.annotation.Nullable java.lang.String typeName) {
    this.typeName = typeName;
    return this;
  }

  public void unsetTypeName() {
    this.typeName = null;
  }

  /** Returns true if field typeName is set (has been assigned a value) and false otherwise */
  public boolean isSetTypeName() {
    return this.typeName != null;
  }

  public void setTypeNameIsSet(boolean value) {
    if (!value) {
      this.typeName = null;
    }
  }

  public int getChildrenSize() {
    return (this.children == null) ? 0 : this.children.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<MongoNode> getChildrenIterator() {
    return (this.children == null) ? null : this.children.iterator();
  }

  public void addToChildren(MongoNode elem) {
    if (this.children == null) {
      this.children = new java.util.ArrayList<MongoNode>();
    }
    this.children.add(elem);
  }

  /**
   * DOCUMENT: the fields in document order, each with its name. ARRAY: the items. OTHER javascriptWithScope: the fields of
   * the scope document, each with its name
   */
  @org.apache.thrift.annotation.Nullable
  public java.util.List<MongoNode> getChildren() {
    return this.children;
  }

  /**
   * DOCUMENT: the fields in document order, each with its name. ARRAY: the items. OTHER javascriptWithScope: the fields of
   * the scope document, each with its name
   */
  public MongoNode setChildren(@org.apache.thrift.annotation.Nullable java.util.List<MongoNode> children) {
    this.children = children;
    return this;
  }

  public void unsetChildren() {
    this.children = null;
  }

  /** Returns true if field children is set (has been assigned a value) and false otherwise */
  public boolean isSetChildren() {
    return this.children != null;
  }

  public void setChildrenIsSet(boolean value) {
    if (!value) {
      this.children = null;
    }
  }

  /**
   * OTHER regex: the flags, for example "im"; empty when there are none
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOptions() {
    return this.options;
  }

  /**
   * OTHER regex: the flags, for example "im"; empty when there are none
   */
  public MongoNode setOptions(@org.apache.thrift.annotation.Nullable java.lang.String options) {
    this.options = options;
    return this;
  }

  public void unsetOptions() {
    this.options = null;
  }

  /** Returns true if field options is set (has been assigned a value) and false otherwise */
  public boolean isSetOptions() {
    return this.options != null;
  }

  public void setOptionsIsSet(boolean value) {
    if (!value) {
      this.options = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case KIND:
      if (value == null) {
        unsetKind();
      } else {
        setKind((MongoNodeKind)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case BOOL_VALUE:
      if (value == null) {
        unsetBoolValue();
      } else {
        setBoolValue((java.lang.Boolean)value);
      }
      break;

    case INT_VALUE:
      if (value == null) {
        unsetIntValue();
      } else {
        setIntValue((java.lang.Integer)value);
      }
      break;

    case LONG_VALUE:
      if (value == null) {
        unsetLongValue();
      } else {
        setLongValue((java.lang.Long)value);
      }
      break;

    case DOUBLE_VALUE:
      if (value == null) {
        unsetDoubleValue();
      } else {
        setDoubleValue((java.lang.Double)value);
      }
      break;

    case TEXT:
      if (value == null) {
        unsetText();
      } else {
        setText((java.lang.String)value);
      }
      break;

    case BYTES:
      if (value == null) {
        unsetBytes();
      } else {
        if (value instanceof byte[]) {
          setBytes((byte[])value);
        } else {
          setBytes((java.nio.ByteBuffer)value);
        }
      }
      break;

    case BINARY_SUBTYPE:
      if (value == null) {
        unsetBinarySubtype();
      } else {
        setBinarySubtype((java.lang.Byte)value);
      }
      break;

    case TYPE_NAME:
      if (value == null) {
        unsetTypeName();
      } else {
        setTypeName((java.lang.String)value);
      }
      break;

    case CHILDREN:
      if (value == null) {
        unsetChildren();
      } else {
        setChildren((java.util.List<MongoNode>)value);
      }
      break;

    case OPTIONS:
      if (value == null) {
        unsetOptions();
      } else {
        setOptions((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case KIND:
      return getKind();

    case NAME:
      return getName();

    case BOOL_VALUE:
      return isBoolValue();

    case INT_VALUE:
      return getIntValue();

    case LONG_VALUE:
      return getLongValue();

    case DOUBLE_VALUE:
      return getDoubleValue();

    case TEXT:
      return getText();

    case BYTES:
      return getBytes();

    case BINARY_SUBTYPE:
      return getBinarySubtype();

    case TYPE_NAME:
      return getTypeName();

    case CHILDREN:
      return getChildren();

    case OPTIONS:
      return getOptions();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case KIND:
      return isSetKind();
    case NAME:
      return isSetName();
    case BOOL_VALUE:
      return isSetBoolValue();
    case INT_VALUE:
      return isSetIntValue();
    case LONG_VALUE:
      return isSetLongValue();
    case DOUBLE_VALUE:
      return isSetDoubleValue();
    case TEXT:
      return isSetText();
    case BYTES:
      return isSetBytes();
    case BINARY_SUBTYPE:
      return isSetBinarySubtype();
    case TYPE_NAME:
      return isSetTypeName();
    case CHILDREN:
      return isSetChildren();
    case OPTIONS:
      return isSetOptions();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof MongoNode)
      return this.equals((MongoNode)that);
    return false;
  }

  public boolean equals(MongoNode that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_kind = true && this.isSetKind();
    boolean that_present_kind = true && that.isSetKind();
    if (this_present_kind || that_present_kind) {
      if (!(this_present_kind && that_present_kind))
        return false;
      if (!this.kind.equals(that.kind))
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_boolValue = true && this.isSetBoolValue();
    boolean that_present_boolValue = true && that.isSetBoolValue();
    if (this_present_boolValue || that_present_boolValue) {
      if (!(this_present_boolValue && that_present_boolValue))
        return false;
      if (this.boolValue != that.boolValue)
        return false;
    }

    boolean this_present_intValue = true && this.isSetIntValue();
    boolean that_present_intValue = true && that.isSetIntValue();
    if (this_present_intValue || that_present_intValue) {
      if (!(this_present_intValue && that_present_intValue))
        return false;
      if (this.intValue != that.intValue)
        return false;
    }

    boolean this_present_longValue = true && this.isSetLongValue();
    boolean that_present_longValue = true && that.isSetLongValue();
    if (this_present_longValue || that_present_longValue) {
      if (!(this_present_longValue && that_present_longValue))
        return false;
      if (this.longValue != that.longValue)
        return false;
    }

    boolean this_present_doubleValue = true && this.isSetDoubleValue();
    boolean that_present_doubleValue = true && that.isSetDoubleValue();
    if (this_present_doubleValue || that_present_doubleValue) {
      if (!(this_present_doubleValue && that_present_doubleValue))
        return false;
      if (this.doubleValue != that.doubleValue)
        return false;
    }

    boolean this_present_text = true && this.isSetText();
    boolean that_present_text = true && that.isSetText();
    if (this_present_text || that_present_text) {
      if (!(this_present_text && that_present_text))
        return false;
      if (!this.text.equals(that.text))
        return false;
    }

    boolean this_present_bytes = true && this.isSetBytes();
    boolean that_present_bytes = true && that.isSetBytes();
    if (this_present_bytes || that_present_bytes) {
      if (!(this_present_bytes && that_present_bytes))
        return false;
      if (!this.bytes.equals(that.bytes))
        return false;
    }

    boolean this_present_binarySubtype = true && this.isSetBinarySubtype();
    boolean that_present_binarySubtype = true && that.isSetBinarySubtype();
    if (this_present_binarySubtype || that_present_binarySubtype) {
      if (!(this_present_binarySubtype && that_present_binarySubtype))
        return false;
      if (this.binarySubtype != that.binarySubtype)
        return false;
    }

    boolean this_present_typeName = true && this.isSetTypeName();
    boolean that_present_typeName = true && that.isSetTypeName();
    if (this_present_typeName || that_present_typeName) {
      if (!(this_present_typeName && that_present_typeName))
        return false;
      if (!this.typeName.equals(that.typeName))
        return false;
    }

    boolean this_present_children = true && this.isSetChildren();
    boolean that_present_children = true && that.isSetChildren();
    if (this_present_children || that_present_children) {
      if (!(this_present_children && that_present_children))
        return false;
      if (!this.children.equals(that.children))
        return false;
    }

    boolean this_present_options = true && this.isSetOptions();
    boolean that_present_options = true && that.isSetOptions();
    if (this_present_options || that_present_options) {
      if (!(this_present_options && that_present_options))
        return false;
      if (!this.options.equals(that.options))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetKind()) ? 131071 : 524287);
    if (isSetKind())
      hashCode = hashCode * 8191 + kind.getValue();

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((isSetBoolValue()) ? 131071 : 524287);
    if (isSetBoolValue())
      hashCode = hashCode * 8191 + ((boolValue) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetIntValue()) ? 131071 : 524287);
    if (isSetIntValue())
      hashCode = hashCode * 8191 + intValue;

    hashCode = hashCode * 8191 + ((isSetLongValue()) ? 131071 : 524287);
    if (isSetLongValue())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(longValue);

    hashCode = hashCode * 8191 + ((isSetDoubleValue()) ? 131071 : 524287);
    if (isSetDoubleValue())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(doubleValue);

    hashCode = hashCode * 8191 + ((isSetText()) ? 131071 : 524287);
    if (isSetText())
      hashCode = hashCode * 8191 + text.hashCode();

    hashCode = hashCode * 8191 + ((isSetBytes()) ? 131071 : 524287);
    if (isSetBytes())
      hashCode = hashCode * 8191 + bytes.hashCode();

    hashCode = hashCode * 8191 + ((isSetBinarySubtype()) ? 131071 : 524287);
    if (isSetBinarySubtype())
      hashCode = hashCode * 8191 + (int) (binarySubtype);

    hashCode = hashCode * 8191 + ((isSetTypeName()) ? 131071 : 524287);
    if (isSetTypeName())
      hashCode = hashCode * 8191 + typeName.hashCode();

    hashCode = hashCode * 8191 + ((isSetChildren()) ? 131071 : 524287);
    if (isSetChildren())
      hashCode = hashCode * 8191 + children.hashCode();

    hashCode = hashCode * 8191 + ((isSetOptions()) ? 131071 : 524287);
    if (isSetOptions())
      hashCode = hashCode * 8191 + options.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(MongoNode other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetKind(), other.isSetKind());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKind()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kind, other.kind);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetName(), other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBoolValue(), other.isSetBoolValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBoolValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.boolValue, other.boolValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIntValue(), other.isSetIntValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIntValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.intValue, other.intValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLongValue(), other.isSetLongValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.longValue, other.longValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDoubleValue(), other.isSetDoubleValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDoubleValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.doubleValue, other.doubleValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetText(), other.isSetText());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetText()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.text, other.text);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBytes(), other.isSetBytes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBytes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bytes, other.bytes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetBinarySubtype(), other.isSetBinarySubtype());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBinarySubtype()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.binarySubtype, other.binarySubtype);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTypeName(), other.isSetTypeName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTypeName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.typeName, other.typeName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetChildren(), other.isSetChildren());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChildren()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.children, other.children);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOptions(), other.isSetOptions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOptions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.options, other.options);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("MongoNode(");
    boolean first = true;

    sb.append("kind:");
    if (this.kind == null) {
      sb.append("null");
    } else {
      sb.append(this.kind);
    }
    first = false;
    if (isSetName()) {
      if (!first) sb.append(", ");
      sb.append("name:");
      if (this.name == null) {
        sb.append("null");
      } else {
        sb.append(this.name);
      }
      first = false;
    }
    if (isSetBoolValue()) {
      if (!first) sb.append(", ");
      sb.append("boolValue:");
      sb.append(this.boolValue);
      first = false;
    }
    if (isSetIntValue()) {
      if (!first) sb.append(", ");
      sb.append("intValue:");
      sb.append(this.intValue);
      first = false;
    }
    if (isSetLongValue()) {
      if (!first) sb.append(", ");
      sb.append("longValue:");
      sb.append(this.longValue);
      first = false;
    }
    if (isSetDoubleValue()) {
      if (!first) sb.append(", ");
      sb.append("doubleValue:");
      sb.append(this.doubleValue);
      first = false;
    }
    if (isSetText()) {
      if (!first) sb.append(", ");
      sb.append("text:");
      if (this.text == null) {
        sb.append("null");
      } else {
        sb.append(this.text);
      }
      first = false;
    }
    if (isSetBytes()) {
      if (!first) sb.append(", ");
      sb.append("bytes:");
      if (this.bytes == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.bytes, sb);
      }
      first = false;
    }
    if (isSetBinarySubtype()) {
      if (!first) sb.append(", ");
      sb.append("binarySubtype:");
      sb.append(this.binarySubtype);
      first = false;
    }
    if (isSetTypeName()) {
      if (!first) sb.append(", ");
      sb.append("typeName:");
      if (this.typeName == null) {
        sb.append("null");
      } else {
        sb.append(this.typeName);
      }
      first = false;
    }
    if (isSetChildren()) {
      if (!first) sb.append(", ");
      sb.append("children:");
      if (this.children == null) {
        sb.append("null");
      } else {
        sb.append(this.children);
      }
      first = false;
    }
    if (isSetOptions()) {
      if (!first) sb.append(", ");
      sb.append("options:");
      if (this.options == null) {
        sb.append("null");
      } else {
        sb.append(this.options);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MongoNodeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MongoNodeStandardScheme getScheme() {
      return new MongoNodeStandardScheme();
    }
  }

  private static class MongoNodeStandardScheme extends org.apache.thrift.scheme.StandardScheme<MongoNode> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, MongoNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KIND
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.kind = consulo.database.mongo.rt.shared.MongoNodeKind.findByValue(iprot.readI32());
              struct.setKindIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BOOL_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.boolValue = iprot.readBool();
              struct.setBoolValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // INT_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.intValue = iprot.readI32();
              struct.setIntValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LONG_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.longValue = iprot.readI64();
              struct.setLongValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DOUBLE_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.doubleValue = iprot.readDouble();
              struct.setDoubleValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TEXT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.text = iprot.readString();
              struct.setTextIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // BYTES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.bytes = iprot.readBinary();
              struct.setBytesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // BINARY_SUBTYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.binarySubtype = iprot.readByte();
              struct.setBinarySubtypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // TYPE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.typeName = iprot.readString();
              struct.setTypeNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // CHILDREN
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.children = new java.util.ArrayList<MongoNode>(_list0.size);
                @org.apache.thrift.annotation.Nullable MongoNode _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new MongoNode();
                  _elem1.read(iprot);
                  struct.children.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setChildrenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // OPTIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.options = iprot.readString();
              struct.setOptionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, MongoNode struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.kind != null) {
        oprot.writeFieldBegin(KIND_FIELD_DESC);
        oprot.writeI32(struct.kind.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.name != null) {
        if (struct.isSetName()) {
          oprot.writeFieldBegin(NAME_FIELD_DESC);
          oprot.writeString(struct.name);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetBoolValue()) {
        oprot.writeFieldBegin(BOOL_VALUE_FIELD_DESC);
        oprot.writeBool(struct.boolValue);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIntValue()) {
        oprot.writeFieldBegin(INT_VALUE_FIELD_DESC);
        oprot.writeI32(struct.intValue);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLongValue()) {
        oprot.writeFieldBegin(LONG_VALUE_FIELD_DESC);
        oprot.writeI64(struct.longValue);
        oprot.writeFieldEnd();
      }
      if (struct.isSetDoubleValue()) {
        oprot.writeFieldBegin(DOUBLE_VALUE_FIELD_DESC);
        oprot.writeDouble(struct.doubleValue);
        oprot.writeFieldEnd();
      }
      if (struct.text != null) {
        if (struct.isSetText()) {
          oprot.writeFieldBegin(TEXT_FIELD_DESC);
          oprot.writeString(struct.text);
          oprot.writeFieldEnd();
        }
      }
      if (struct.bytes != null) {
        if (struct.isSetBytes()) {
          oprot.writeFieldBegin(BYTES_FIELD_DESC);
          oprot.writeBinary(struct.bytes);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetBinarySubtype()) {
        oprot.writeFieldBegin(BINARY_SUBTYPE_FIELD_DESC);
        oprot.writeByte(struct.binarySubtype);
        oprot.writeFieldEnd();
      }
      if (struct.typeName != null) {
        if (struct.isSetTypeName()) {
          oprot.writeFieldBegin(TYPE_NAME_FIELD_DESC);
          oprot.writeString(struct.typeName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.children != null) {
        if (struct.isSetChildren()) {
          oprot.writeFieldBegin(CHILDREN_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.children.size()));
            for (MongoNode _iter3 : struct.children)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.options != null) {
        if (struct.isSetOptions()) {
          oprot.writeFieldBegin(OPTIONS_FIELD_DESC);
          oprot.writeString(struct.options);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MongoNodeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public MongoNodeTupleScheme getScheme() {
      return new MongoNodeTupleScheme();
    }
  }

  private static class MongoNodeTupleScheme extends org.apache.thrift.scheme.TupleScheme<MongoNode> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MongoNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetKind()) {
        optionals.set(0);
      }
      if (struct.isSetName()) {
        optionals.set(1);
      }
      if (struct.isSetBoolValue()) {
        optionals.set(2);
      }
      if (struct.isSetIntValue()) {
        optionals.set(3);
      }
      if (struct.isSetLongValue()) {
        optionals.set(4);
      }
      if (struct.isSetDoubleValue()) {
        optionals.set(5);
      }
      if (struct.isSetText()) {
        optionals.set(6);
      }
      if (struct.isSetBytes()) {
        optionals.set(7);
      }
      if (struct.isSetBinarySubtype()) {
        optionals.set(8);
      }
      if (struct.isSetTypeName()) {
        optionals.set(9);
      }
      if (struct.isSetChildren()) {
        optionals.set(10);
      }
      if (struct.isSetOptions()) {
        optionals.set(11);
      }
      oprot.writeBitSet(optionals, 12);
      if (struct.isSetKind()) {
        oprot.writeI32(struct.kind.getValue());
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetBoolValue()) {
        oprot.writeBool(struct.boolValue);
      }
      if (struct.isSetIntValue()) {
        oprot.writeI32(struct.intValue);
      }
      if (struct.isSetLongValue()) {
        oprot.writeI64(struct.longValue);
      }
      if (struct.isSetDoubleValue()) {
        oprot.writeDouble(struct.doubleValue);
      }
      if (struct.isSetText()) {
        oprot.writeString(struct.text);
      }
      if (struct.isSetBytes()) {
        oprot.writeBinary(struct.bytes);
      }
      if (struct.isSetBinarySubtype()) {
        oprot.writeByte(struct.binarySubtype);
      }
      if (struct.isSetTypeName()) {
        oprot.writeString(struct.typeName);
      }
      if (struct.isSetChildren()) {
        {
          oprot.writeI32(struct.children.size());
          for (MongoNode _iter4 : struct.children)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetOptions()) {
        oprot.writeString(struct.options);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MongoNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(12);
      if (incoming.get(0)) {
        struct.kind = consulo.database.mongo.rt.shared.MongoNodeKind.findByValue(iprot.readI32());
        struct.setKindIsSet(true);
      }
      if (incoming.get(1)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.boolValue = iprot.readBool();
        struct.setBoolValueIsSet(true);
      }
      if (incoming.get(3)) {
        struct.intValue = iprot.readI32();
        struct.setIntValueIsSet(true);
      }
      if (incoming.get(4)) {
        struct.longValue = iprot.readI64();
        struct.setLongValueIsSet(true);
      }
      if (incoming.get(5)) {
        struct.doubleValue = iprot.readDouble();
        struct.setDoubleValueIsSet(true);
      }
      if (incoming.get(6)) {
        struct.text = iprot.readString();
        struct.setTextIsSet(true);
      }
      if (incoming.get(7)) {
        struct.bytes = iprot.readBinary();
        struct.setBytesIsSet(true);
      }
      if (incoming.get(8)) {
        struct.binarySubtype = iprot.readByte();
        struct.setBinarySubtypeIsSet(true);
      }
      if (incoming.get(9)) {
        struct.typeName = iprot.readString();
        struct.setTypeNameIsSet(true);
      }
      if (incoming.get(10)) {
        {
          org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.children = new java.util.ArrayList<MongoNode>(_list5.size);
          @org.apache.thrift.annotation.Nullable MongoNode _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new MongoNode();
            _elem6.read(iprot);
            struct.children.add(_elem6);
          }
        }
        struct.setChildrenIsSet(true);
      }
      if (incoming.get(11)) {
        struct.options = iprot.readString();
        struct.setOptionsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

