/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.database.mongo.rt.shared;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class MongoExecutorConstants {

  /**
   * The runtime prints this prefix and its port on one stdout line once it accepts connections, for example
   * "[mongo-rt-ready] 41234". Nothing else is printed to stdout.
   * 
   * Before that the IDE writes two lines to the stdin of the runtime: the client token, then the server token. Both are random
   * and never appear on the command line. The IDE keeps stdin open: when it is closed, the runtime exits.
   */
  public static final java.lang.String READY_LINE_PREFIX = "[mongo-rt-ready] ";

  /**
   * The runtime listens on this address only, and the IDE connects to it - not to a host name, which may resolve to another
   * loopback address in the other JVM.
   */
  public static final java.lang.String LOOPBACK_HOST = "127.0.0.1";

  public static final java.lang.String MAIN_CLASS = "consulo.database.mongo.rt.Main";

  /**
   * Returned by hello(). The IDE refuses a runtime of another version, for example a stale runtime jar.
   */
  public static final int PROTOCOL_VERSION = 1;

}
