namespace * consulo.database.jdbc.rt.shared

exception FailError
{
	1: string message;

	2: string trace;
}

struct JdbcTable
{
	1: string name;

	2: list<JdbcColum> colums;

	3: string type;

	4: string scheme;

	5: list<JdbcTablePrimaryKey> primaryKeys;
}

struct JdbcTablePrimaryKey
{
	1: string columnName;

	2: i16 keySeq;

	3: string pkName;
}

struct JdbcColum
{
	1: string name;

	2: string type;

	3: i32 jdbcType;

	4: bool nullable;

	5: bool autoGenerated;

	6: bool autoIncrement;

	7: string defaultValue;

	8: i32 size;
}

struct JdbcQueryResult
{
	1: list<string> columns;

	2: list<JdbcQueryRow> rows;
}

struct JdbcQueryRow
{
	1: list<JdbcValue> values;

	2: i64 index;
}

enum JdbcValueType
{
	_int,
	_string,
	_bool,
	_long
}

struct JdbcValue
{
	1: JdbcValueType type;

	2: optional i32 intValue;

	3: optional string stringValue;

	4: optional bool boolValue;

	5: optional i64 longValue;
}

service JdbcExecutor
{
	void connect(1: string url, 2: map<string, string> properties) throws (1: FailError fr);

	bool testConnection() throws (1: FailError fr);

	list<string> listDatabases() throws (1: FailError fr);

	list<JdbcTable> listTables(1: string databaseName) throws (1: FailError fr);

	JdbcQueryResult runQuery(1: string query, 2: list<JdbcValue> params) throws (1: FailError fr);

	void setDatabase(1: string dbName) throws (1: FailError fr);
}

