/*
 * Copyright 2013-2020 consulo.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package consulo.database.jdbc.rt;

import consulo.database.jdbc.rt.shared.*;
import org.apache.thrift.TException;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.math.BigDecimal;
import java.sql.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Properties;

/**
 * @author VISTALL
 * @since 2020-08-16
 */
public class JdbcExecutorImpl implements JdbcExecutor.Iface {
    // guards against a driver which never ends its results or links its warnings into a cycle
    private static final int MAX_STATEMENT_RESULTS = 10_000;
    private static final int MAX_WARNINGS = 1_000;

    private Connection myConnection;
    private String myUrl;
    private Properties myProperties;

    @Override
    public void connect(String url, Map<String, String> params) throws FailError, TException {
        myUrl = url;
        myProperties = new Properties();
        for (Map.Entry<String, String> entry : params.entrySet()) {
            // properties can not hold null - a key without value is not passed to the driver at all
            if (entry.getValue() != null) {
                myProperties.setProperty(entry.getKey(), entry.getValue());
            }
        }

        try {
            myConnection = DriverManager.getConnection(myUrl, myProperties);
        }
        catch (Throwable e) {
            e.printStackTrace();

            throw createFailError(e);
        }
    }

    @Override
    public boolean testConnection() throws FailError, TException {
        return call(param ->
        {
            param.isValid(10_000);
            return true;
        });
    }

    @Override
    public List<String> listDatabases() throws FailError, TException {
        return call(conn ->
        {
            List<String> databases = new ArrayList<>();

            DatabaseMetaData metaData = conn.getMetaData();
            ResultSet tables = metaData.getCatalogs();
            while (tables.next()) {
                databases.add(tables.getString("TABLE_CAT"));
            }
            return databases;
        });
    }

    @Override
    public List<JdbcTable> listTables(String databaseName) throws FailError, TException {
        return call(conn ->
        {
            Connection targetConn = openConnectionToDatabase(databaseName);

            try {
                Connection useConn = targetConn != null ? targetConn : conn;

                List<JdbcTable> list = new ArrayList<>();

                DatabaseMetaData md = useConn.getMetaData();
                ResultSet rs = md.getTables(databaseName, null, "%", null);
                while (rs.next()) {
                    String tableSchem = rs.getString("TABLE_SCHEM");
                    String tableName = rs.getString("TABLE_NAME");
                    String type = rs.getString("TABLE_TYPE");

                    List<JdbcColum> columList = new ArrayList<>();

                    ResultSet columns = md.getColumns(databaseName, null, tableName, null);
                    while (columns.next()) {
                        String colName = columns.getString("COLUMN_NAME");
                        int jdbcColType = columns.getInt("DATA_TYPE");
                        int size = columns.getInt("COLUMN_SIZE");
                        String colType = columns.getString("TYPE_NAME");
                        boolean autoGenerated = "YES".equals(columns.getString("IS_GENERATEDCOLUMN"));
                        boolean nullable = "YES".equals(columns.getString("IS_NULLABLE"));
                        boolean isAutoincrement = "YES".equals(columns.getString("IS_AUTOINCREMENT"));
                        String defaultValue = columns.getString("COLUMN_DEF");

                        columList.add(new JdbcColum(colName, colType, jdbcColType, nullable, autoGenerated, isAutoincrement, defaultValue, size));
                    }

                    List<JdbcTablePrimaryKey> primaryKeyList = new ArrayList<>();
                    ResultSet primaryKeys = md.getPrimaryKeys(databaseName, tableSchem, tableName);
                    while (primaryKeys.next()) {
                        String columnName = primaryKeys.getString("COLUMN_NAME");
                        short keySeq = primaryKeys.getShort("KEY_SEQ");
                        String pkName = primaryKeys.getString("PK_NAME");

                        primaryKeyList.add(new JdbcTablePrimaryKey(columnName, keySeq, pkName));
                    }

                    list.add(new JdbcTable(tableName, columList, type, tableSchem, primaryKeyList));
                }

                return list;
            }
            finally {
                if (targetConn != null) {
                    targetConn.close();
                }
            }
        });
    }

    @Override
    public JdbcExecutionResult execute(String query, List<JdbcValue> params, int maxRows, int offset) throws FailError, TException {
        return call(conn ->
        {
            int skipRows = Math.max(offset, 0);
            int limitRows = Math.max(maxRows, 0);

            List<JdbcStatementResult> results = new ArrayList<>();
            List<String> warnings = new ArrayList<>();

            conn.clearWarnings();

            // without parameters a plain statement runs the text as is: a ? in it (an operator, a string) is no placeholder
            boolean prepared = !params.isEmpty();
            Statement statement = prepared ? conn.prepareStatement(query) : conn.createStatement();
            try {
                if (prepared) {
                    bindParameters((PreparedStatement) statement, params);
                }

                if (limitRows > 0) {
                    // one row more than requested tells whether more rows follow
                    long statementMaxRows = (long) skipRows + limitRows + 1;
                    statement.setMaxRows((int) Math.min(statementMaxRows, Integer.MAX_VALUE));
                }

                boolean isResultSet = prepared ? ((PreparedStatement) statement).execute() : statement.execute(query);
                while (results.size() < MAX_STATEMENT_RESULTS) {
                    if (isResultSet) {
                        ResultSet resultSet = statement.getResultSet();
                        if (resultSet == null) {
                            break;
                        }

                        try {
                            results.add(new JdbcStatementResult().setResultSet(readResultSet(resultSet, skipRows, limitRows)));

                            collectWarnings(resultSet.getWarnings(), warnings);
                        }
                        finally {
                            closeQuietly(resultSet);
                        }
                    }
                    else {
                        int updateCount = statement.getUpdateCount();
                        if (updateCount == -1) {
                            break;
                        }

                        results.add(new JdbcStatementResult().setUpdateCount(updateCount));
                    }

                    isResultSet = statement.getMoreResults();
                }

                collectWarnings(statement.getWarnings(), warnings);
                collectWarnings(conn.getWarnings(), warnings);
            }
            finally {
                closeQuietly(statement);
            }

            return new JdbcExecutionResult(results, warnings);
        });
    }

    private static JdbcResultSet readResultSet(ResultSet resultSet, int skipRows, int limitRows) throws SQLException {
        ResultSetMetaData metaData = resultSet.getMetaData();
        int columnCount = metaData == null ? 0 : metaData.getColumnCount();

        List<JdbcColumnMeta> columns = new ArrayList<>(columnCount);
        JdbcColumnKind[] kinds = new JdbcColumnKind[columnCount];
        for (int i = 0; i < columnCount; i++) {
            JdbcColumnMeta column = readColumnMeta(metaData, i + 1);
            columns.add(column);
            kinds[i] = JdbcColumnKind.of(column.getJdbcType(), column.getTypeName(), column.getPrecision());
        }

        List<JdbcQueryRow> rows = new ArrayList<>();
        boolean hasMore = false;
        long rowIndex = 0;
        while (resultSet.next()) {
            if (rowIndex < skipRows) {
                rowIndex++;
                continue;
            }

            if (limitRows > 0 && rows.size() >= limitRows) {
                hasMore = true;
                break;
            }

            List<JdbcValue> values = new ArrayList<>(columnCount);
            for (int i = 0; i < columnCount; i++) {
                values.add(JdbcValueReader.read(resultSet, i + 1, kinds[i]));
            }

            rows.add(new JdbcQueryRow(values, rowIndex));
            rowIndex++;
        }

        return new JdbcResultSet(columns, rows, hasMore);
    }

    private static JdbcColumnMeta readColumnMeta(ResultSetMetaData metaData, int index) throws SQLException {
        JdbcColumnMeta column = new JdbcColumnMeta();

        String columnName = metaData.getColumnName(index);
        String label = metaData.getColumnLabel(index);

        column.setColumnName(columnName == null ? "" : columnName);
        column.setLabel(label == null || label.isEmpty() ? column.getColumnName() : label);
        column.setJdbcType(metaData.getColumnType(index));

        String typeName = metaData.getColumnTypeName(index);
        column.setTypeName(typeName == null ? "" : typeName);

        // the optional parts of the metadata - some drivers throw instead of answering
        try {
            column.setPrecision(metaData.getPrecision(index));
        }
        catch (SQLException | RuntimeException e) {
            column.setPrecision(0);
        }

        try {
            column.setScale(metaData.getScale(index));
        }
        catch (SQLException | RuntimeException e) {
            column.setScale(0);
        }

        try {
            column.setNullable(metaData.isNullable(index));
        }
        catch (SQLException | RuntimeException e) {
            column.setNullable(ResultSetMetaData.columnNullableUnknown);
        }

        try {
            column.setAutoIncrement(metaData.isAutoIncrement(index));
        }
        catch (SQLException | RuntimeException e) {
            column.setAutoIncrement(false);
        }

        String tableName = readOptionalName(metaData, index, NameKind.TABLE);
        if (tableName != null) {
            column.setTableName(tableName);
        }

        String schemaName = readOptionalName(metaData, index, NameKind.SCHEMA);
        if (schemaName != null) {
            column.setSchemaName(schemaName);
        }

        String catalogName = readOptionalName(metaData, index, NameKind.CATALOG);
        if (catalogName != null) {
            column.setCatalogName(catalogName);
        }

        return column;
    }

    private enum NameKind {
        TABLE,
        SCHEMA,
        CATALOG
    }

    /**
     * @return the name, or null when the driver does not know it - drivers answer an empty string for that
     */
    private static String readOptionalName(ResultSetMetaData metaData, int index, NameKind kind) {
        try {
            String name = switch (kind) {
                case TABLE -> metaData.getTableName(index);
                case SCHEMA -> metaData.getSchemaName(index);
                case CATALOG -> metaData.getCatalogName(index);
            };
            return name == null || name.isEmpty() ? null : name;
        }
        catch (SQLException | RuntimeException e) {
            return null;
        }
    }

    private static void bindParameters(PreparedStatement statement, List<JdbcValue> params) throws SQLException {
        int index = 1;
        for (JdbcValue param : params) {
            bindParameter(statement, index, param);
            index++;
        }
    }

    private static void bindParameter(PreparedStatement statement, int index, JdbcValue param) throws SQLException {
        JdbcValueType type = param.getType();
        // an unset value field is SQL NULL too
        if (type == null || type == JdbcValueType._null || !isValueSet(param, type)) {
            statement.setNull(index, getNullSqlType(type));
            return;
        }

        switch (type) {
            case _int -> statement.setInt(index, param.getIntValue());
            case _long -> statement.setLong(index, param.getLongValue());
            case _bool -> statement.setBoolean(index, param.isBoolValue());
            case _double -> statement.setDouble(index, param.getDoubleValue());
            case _string -> statement.setString(index, param.getStringValue());
            case _decimal -> statement.setBigDecimal(index, new BigDecimal(param.getStringValue()));
            case _date -> {
                LocalDate date = LocalDate.parse(param.getStringValue());
                setObject(statement, index, date, () -> statement.setDate(index, Date.valueOf(date)));
            }
            case _time -> {
                String text = param.getStringValue();
                if (JdbcValueReader.hasOffset(text)) {
                    OffsetTime time = OffsetTime.parse(text);
                    setObject(statement, index, time, () -> statement.setString(index, text));
                }
                else {
                    LocalTime time = LocalTime.parse(text);
                    setObject(statement, index, time, () -> statement.setTime(index, Time.valueOf(time)));
                }
            }
            case _timestamp -> {
                LocalDateTime dateTime = LocalDateTime.parse(param.getStringValue());
                setObject(statement, index, dateTime, () -> statement.setTimestamp(index, Timestamp.valueOf(dateTime)));
            }
            case _timestamptz -> {
                OffsetDateTime dateTime = OffsetDateTime.parse(param.getStringValue());
                setObject(statement, index, dateTime, () -> statement.setTimestamp(index, Timestamp.from(dateTime.toInstant())));
            }
            case _bytes -> statement.setBytes(index, param.getBytesValue());
            // the text goes to the server untyped, so it can be cast to json, uuid, interval and so on
            case _other -> statement.setObject(index, param.getStringValue(), Types.OTHER);
            case _array -> throw new SQLFeatureNotSupportedException("Array parameters are not supported");
            default -> throw new SQLFeatureNotSupportedException(type + " parameters are not supported");
        }
    }

    private interface SqlAction {
        void run() throws SQLException;
    }

    /**
     * java.time objects need a driver with JDBC 4.2 support - an older one gets the java.sql value
     */
    private static void setObject(PreparedStatement statement, int index, Object value, SqlAction fallback) throws SQLException {
        try {
            statement.setObject(index, value);
        }
        catch (SQLException | RuntimeException e) {
            fallback.run();
        }
    }

    private static boolean isValueSet(JdbcValue value, JdbcValueType type) {
        return switch (type) {
            case _int -> value.isSetIntValue();
            case _long -> value.isSetLongValue();
            case _bool -> value.isSetBoolValue();
            case _double -> value.isSetDoubleValue();
            case _bytes -> value.isSetBytesValue();
            case _array -> value.isSetArrayValue();
            case _null -> false;
            default -> value.isSetStringValue();
        };
    }

    private static int getNullSqlType(JdbcValueType type) {
        if (type == null) {
            return Types.NULL;
        }

        return switch (type) {
            case _int -> Types.INTEGER;
            case _long -> Types.BIGINT;
            case _bool -> Types.BOOLEAN;
            case _double -> Types.DOUBLE;
            case _string -> Types.VARCHAR;
            case _decimal -> Types.DECIMAL;
            case _date -> Types.DATE;
            case _time -> Types.TIME;
            case _timestamp -> Types.TIMESTAMP;
            case _timestamptz -> Types.TIMESTAMP_WITH_TIMEZONE;
            case _bytes -> Types.VARBINARY;
            case _array -> Types.ARRAY;
            case _other -> Types.OTHER;
            default -> Types.NULL;
        };
    }

    private static void collectWarnings(SQLWarning warning, List<String> warnings) {
        SQLWarning current = warning;
        int count = 0;
        while (current != null && count < MAX_WARNINGS) {
            String message = current.getMessage();
            warnings.add(message == null ? current.toString() : message);

            current = current.getNextWarning();
            count++;
        }
    }

    private static void closeQuietly(AutoCloseable closeable) {
        try {
            closeable.close();
        }
        catch (Exception ignored) {
        }
    }

    @Override
    public void setDatabase(String dbName) throws FailError, TException {
        call(param ->
        {
            Connection newConn = openConnectionToDatabase(dbName);
            if (newConn != null) {
                Connection oldConn = myConnection;
                myConnection = newConn;
                oldConn.close();
            }
            return null;
        });
    }

    private Connection openConnectionToDatabase(String databaseName) throws SQLException {
        String currentCatalog = myConnection.getCatalog();
        if (databaseName.equals(currentCatalog)) {
            return null;
        }

        // PostgreSQL requires a separate connection per database
        String newUrl = replaceDatabaseInUrl(myUrl, databaseName);
        return DriverManager.getConnection(newUrl, myProperties);
    }

    private static String replaceDatabaseInUrl(String url, String databaseName) {
        // URL format: jdbc:TYPE://host:port/database
        // Find the '/' after '://'
        int schemeEnd = url.indexOf("://");
        if (schemeEnd < 0) {
            return url + "/" + databaseName;
        }

        int pathStart = url.indexOf('/', schemeEnd + 3);
        if (pathStart < 0) {
            return url + "/" + databaseName;
        }

        return url.substring(0, pathStart + 1) + databaseName;
    }

    private static String getStackTrace(Throwable t) {
        StringWriter writer = new StringWriter();
        try (PrintWriter printWriter = new PrintWriter(writer)) {
            t.printStackTrace(printWriter);
        }
        return writer.getBuffer().toString();
    }

    private static FailError createFailError(Throwable e) {
        String message = e.getMessage();

        FailError error = new FailError(message == null ? e.getClass().getName() : message, getStackTrace(e));

        SQLException sqlException = findSqlException(e);
        if (sqlException != null) {
            String sqlState = sqlException.getSQLState();
            if (sqlState != null) {
                error.setSqlState(sqlState);
            }
            error.setVendorCode(sqlException.getErrorCode());
        }
        return error;
    }

    private static SQLException findSqlException(Throwable e) {
        Throwable current = e;
        // the depth limit guards against a cause chain with a cycle
        for (int depth = 0; current != null && depth < 64; depth++) {
            if (current instanceof SQLException sqlException) {
                return sqlException;
            }
            current = current.getCause();
        }
        return null;
    }

    protected <T> T call(ThwroableFunction<T, Connection> callable) throws FailError {
        try {
            if (myConnection == null) {
                throw new SQLException("Not connected");
            }

            return callable.call(myConnection);
        }
        catch (Throwable e) {
            e.printStackTrace();

            throw createFailError(e);
        }
    }
}
